name: CI

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master

jobs:
  build_and_test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Install deps
      run: yarn install

    # - name: Test MacOs
    #   if: matrix.os == 'macos-latest'
    #   run: yarn test

    - name: Test Windows
      if: matrix.os == 'windows-latest'
      run:  |
          yarn test

    - name: Test Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
          export DISPLAY=:99.0
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm i -g xvfb-maybe
          xvfb-maybe yarn test
