name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Node.js, NPM and Yarn
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Install deps
      run: yarn install

    - name: Test
      run: yarn test
        
        # |
        #   if [[ "$OSTYPE" == "linux-gnu" ]]; then
        #     export DISPLAY=:99.0
        #     Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        #   fi
        #   npm i -g xvfb-maybe
        #   xvfb-maybe yarn test